from django.urls import include, path

from . import views

urlpatterns = [
    path("portal/", include("inventory.portal_urls")),
    path("show-deleted/toggle/", views.toggle_show_deleted, name="toggle_show_deleted"),
    path("accounts/preferences/", views.user_preferences_view, name="user_preferences"),
    path("messages/", views.direct_messages_view, name="direct_messages"),
    path("about/", views.about_site, name="about_site"),
    path("api/docs/", views.api_docs, name="api_docs"),
    path("quality/", views.quality_report_view, name="quality_report"),
    path("tools/data/", views.data_tools, name="data_tools"),
    path("tools/data/import-json/", views.import_json_backup, name="import_json_backup"),
    path("tools/data/backup-json/", views.download_json_backup, name="download_json_backup"),
    path("tools/data/backup-sqlite/", views.download_sqlite_backup, name="download_sqlite_backup"),
    path("tools/data/backup-postgresql/", views.download_postgresql_backup, name="download_postgresql_backup"),
    path("tools/data/import-postgresql-dump/", views.import_postgresql_dump, name="import_postgresql_dump"),
    path("tools/data/export-portal-logs/", views.export_portal_logs_csv, name="export_portal_logs_csv"),
    path("", views.analytics, name="analytics"),
    path("analytics/export-csv-zip/", views.analytics_export_csv_zip, name="analytics_export_csv_zip"),
    path("analytics/print/", views.analytics_print, name="analytics_print"),
    path("equipment/", views.equipment_list, name="equipment_list"),
    path("equipment/export-csv/", views.equipment_export_csv, name="equipment_export_csv"),
    path("equipment/print/", views.equipment_print, name="equipment_print"),
    path("equipment/<int:equipment_id>/qr/", views.equipment_qr, name="equipment_qr"),
    path("usage/", views.usage_history, name="usage_history"),
    path("usage/export-csv/", views.usage_export_csv, name="usage_export_csv"),
    path("usage/print/", views.usage_print, name="usage_print"),
    path("usage/new/", views.usage_create, name="usage_create"),
    path("requests/", views.request_history, name="request_history"),
    path("requests/export-csv/", views.request_export_csv, name="request_export_csv"),
    path("requests/print/", views.request_print, name="request_print"),
    path("requests/new/", views.request_create, name="request_create"),
    path("requests/<int:request_id>/", views.request_detail, name="request_detail"),
    path("requests/<int:request_id>/status/", views.request_update_status, name="request_update_status"),
    path("search/", views.inventory_search, name="inventory_search"),
    path("workplaces/", views.workplaces, name="workplaces"),
    path("cabinets/", views.cabinets, name="cabinets"),
    path("checkouts/", views.checkouts, name="checkouts"),
    path("checkouts/new/", views.checkout_create, name="checkout_create"),
    path("checkouts/<int:checkout_id>/return/", views.checkout_return, name="checkout_return"),
    path("history/", views.history_timeline, name="history"),
    path("reports/", views.reports, name="reports"),
    path("reports/print/", views.reports_print, name="reports_print"),
    path("reports/export/<str:report_type>/", views.reports_export, name="reports_export"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/password-reset/", views.password_reset_request_view, name="password_reset_request"),
    path("accounts/password-reset/confirm/", views.password_reset_confirm_view, name="password_reset_confirm"),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("accounts/register/", views.register_view, name="register"),
    path("accounts/roles/", views.role_assignment, name="role_assignment"),
]
