# Generated by Django 5.2.11 on 2026-04-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplacemember',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('warehouse', 'Склад'), ('sysadmin', 'Системный администратор'), ('builder', 'Строитель')], max_length=20),
        ),
    ]
