# Generated by Django 5.2.11 on 2026-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_workplacemember_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['code'], 'verbose_name': 'Cabinet', 'verbose_name_plural': 'Cabinets'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['name'], 'verbose_name': 'Equipment category', 'verbose_name_plural': 'Equipment categories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['name'], 'verbose_name': 'Workplace', 'verbose_name_plural': 'Workplaces'},
        ),
        migrations.AlterModelOptions(
            name='workplacemember',
            options={'ordering': ['workplace__name', 'user__username'], 'verbose_name': 'Workplace member', 'verbose_name_plural': 'Workplace members'},
        ),
        migrations.AlterField(
            model_name='workplacemember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('warehouse', 'Warehouse'), ('sysadmin', 'Sysadmin'), ('builder', 'Builder')], max_length=20),
        ),
    ]
