# Generated by Django 5.2.11 on 2026-04-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_portal_and_i18n_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme_variant", models.CharField(choices=[("default", "Soft light"), ("contrast", "High contrast")], default="default", max_length=20)),
                ("page_size", models.PositiveSmallIntegerField(choices=[(10, "10"), (25, "25"), (50, "50"), (100, "100")], default=25)),
                (
                    "date_display_format",
                    models.CharField(
                        choices=[("compact", "DD.MM.YYYY HH:MM"), ("iso", "YYYY-MM-DD HH:MM"), ("verbose", "Verbose locale format")],
                        default="compact",
                        max_length=20,
                    ),
                ),
                (
                    "default_timer_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "All timers"), ("active", "Active timers"), ("finished", "Finished timers")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="preferences", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "User preference",
                "verbose_name_plural": "User preferences",
                "ordering": ["user__username"],
            },
        ),
    ]
