# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="default_checkout_status",
            field=models.CharField(blank=True, choices=[("", "All checkouts"), ("active", "Active checkouts"), ("returned", "Returned checkouts")], default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="default_request_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="default_request_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="default_usage_period_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="hotkeys_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="show_hotkey_legend",
            field=models.BooleanField(default=True),
        ),
    ]
