# Generated by Django 5.2.11 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userpreference_extended_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="preferred_language",
            field=models.CharField(default="ru", max_length=10),
        ),
    ]
