# Generated by Django 5.2.11 on 2026-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userpreference_dark_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinet',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'equipment categories'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workplace',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='workplacemember',
            options={'ordering': ['workplace__name', 'user__username']},
        ),
    ]
