# Generated by Django 5.2.11 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cabinet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='date_display_format',
            field=models.CharField(choices=[('compact', 'ДД.ММ.ГГГГ ЧЧ:ММ'), ('iso', 'ГГГГ-ММ-ДД ЧЧ:ММ'), ('verbose', 'Развёрнутый локальный формат')], default='compact', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='default_checkout_status',
            field=models.CharField(blank=True, choices=[('', 'Все выдачи'), ('active', 'Активные выдачи'), ('returned', 'Возвращённые выдачи')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='default_timer_status',
            field=models.CharField(blank=True, choices=[('', 'Все таймеры'), ('active', 'Активные таймеры'), ('finished', 'Завершённые таймеры')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme_variant',
            field=models.CharField(choices=[('default', 'Мягкая светлая'), ('contrast', 'Контрастная'), ('dark', 'Тёмная')], default='default', max_length=20),
        ),
    ]
