# Generated by Django 5.2.11 on 2026-04-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_equipment_supplier'),
        ('core', '0011_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='default_timer_status',
        ),
    ]
