# Generated by Django 5.2.11 on 2026-04-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='map_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
