# Generated by Django 5.2.11 on 2026-05-05 21:03

from django.db import migrations, models


def default_empty_request_status_to_pending(apps, schema_editor):
    UserPreference = apps.get_model("core", "UserPreference")
    UserPreference.objects.filter(default_request_status="").update(default_request_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_cabinet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='default_request_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.RunPython(default_empty_request_status_to_pending, migrations.RunPython.noop),
    ]
