# Generated by Django 5.2.11 on 2026-05-07 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employeeschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='cycle_start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Точка отсчёта для графика 2/2.', verbose_name='Дата начала цикла 2/2'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='schedule_type',
            field=models.CharField(choices=[('5_2', '5/2'), ('2_2', '2/2'), ('custom', 'Кастомный')], default='5_2', max_length=16, verbose_name='Режим графика'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
    ]
