# Generated by Django 5.2.11 on 2026-02-23 18:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('inventory_number', models.CharField(max_length=100, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('is_consumable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('assigned', 'Assigned'), ('checked_out', 'Checked out'), ('repair', 'Repair'), ('retired', 'Retired')], default='in_stock', max_length=20)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('low_stock_threshold', models.PositiveIntegerField(default=0)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('last_inventory_at', models.DateField(blank=True, null=True)),
                ('inventory_interval_days', models.PositiveIntegerField(default=180)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cabinet')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.equipmentcategory')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
                ('workplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workplace')),
            ],
            options={
                'ordering': ['name', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cabinet')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.equipment')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
    ]
