# Generated by Django 5.2.11 on 2026-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('assigned', 'Закреплено'), ('checked_out', 'Выдано'), ('repair', 'В ремонте'), ('retired', 'Списано')], default='in_stock', max_length=20),
        ),
    ]
