# Generated by Django 5.2.11 on 2026-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_equipment_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name', 'inventory_number'], 'verbose_name': 'Equipment item', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmentcheckout',
            options={'ordering': ['-taken_at'], 'verbose_name': 'Equipment checkout', 'verbose_name_plural': 'Equipment checkouts'},
        ),
        migrations.AlterModelOptions(
            name='inventoryadjustment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory adjustment', 'verbose_name_plural': 'Inventory adjustments'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_stock', 'In stock'), ('assigned', 'Assigned'), ('checked_out', 'Checked out'), ('repair', 'Repair'), ('retired', 'Retired')], default='in_stock', max_length=20),
        ),
    ]
