# Generated by Django 5.2.11 on 2026-04-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_portal_and_i18n_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name', 'inventory_number']},
        ),
        migrations.AlterModelOptions(
            name='equipmentcheckout',
            options={'ordering': ['-taken_at']},
        ),
        migrations.AlterModelOptions(
            name='inventoryadjustment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='photo',
        ),
    ]
