# Generated by Django 5.2.11 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('in_stock', 'На складе'), ('assigned', 'Закреплено'), ('checked_out', 'Выдано'), ('repair', 'В ремонте'), ('retired', 'Списано')], default='in_stock', max_length=20),
        ),
    ]
