# Generated by Django 5.2.11 on 2026-04-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_equipment_photo_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
    ]
