# Generated by Django 5.2.11 on 2026-04-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_equipment_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='inventory_interval_days',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_inventory_at',
        ),
    ]
