# Generated by Django 5.2.11 on 2026-05-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_remove_equipment_inventory_interval_days_and_more'),
        ('operations', '0009_equipmentrequest_cabinet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reserved_from', models.DateTimeField(db_index=True)),
                ('reserved_until', models.DateTimeField(db_index=True)),
                ('cancelled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_reservations', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='assets.equipment')),
                ('related_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_reservations', to='operations.equipmentrequest')),
                ('reserved_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_equipment_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['equipment', 'cancelled_at', 'reserved_from', 'reserved_until'], name='assets_equi_equipme_0b5d7f_idx')],
            },
        ),
    ]
