import os

"""
Django settings for TIP project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import importlib.util
from pathlib import Path
from django.utils.translation import gettext_lazy as _

def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-(iae*%=jxqkz_3e^ii(b3ee6tvg_9!((w_bcburtnbc2b&g-^&",
).strip()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}

_allowed_hosts = os.getenv("ALLOWED_HOSTS", "").strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()] if _allowed_hosts else []

# Prometheus в Docker скрейпит http://djangoapp:8000/metrics → Host: djangoapp.
# Если ALLOWED_HOSTS задан только под внешний домен/IP, без сервисного имени — будет 400 DisallowedHost.
# Если переменная ALLOWED_HOSTS не задана: список пустой — Django при DEBUG принимает только localhost,
# а условие ниже не срабатывало → djangoapp не добавлялся → up{job="django"}=0 в Grafana.
_wildcard_allowed = any(h == "*" for h in ALLOWED_HOSTS)
_internal_scrape = os.getenv("INTERNAL_SCRAPE_HOSTS", "djangoapp,web").strip()
if not _wildcard_allowed and _internal_scrape:
    if not ALLOWED_HOSTS and DEBUG:
        ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
    if ALLOWED_HOSTS:
        for _h in (x.strip() for x in _internal_scrape.split(",") if x.strip()):
            if _h not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(_h)

_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()] if _csrf_origins else []


# Application definition

_ANYMAIL_INSTALLED = importlib.util.find_spec("anymail") is not None

INSTALLED_APPS = [
    *(['anymail'] if _ANYMAIL_INSTALLED else []),
    'django_extensions',
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'core',
    'assets',
    'operations',
    'audit',
    'inventory']

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventory.middleware.UserPreferenceLocaleMiddleware',
    'inventory.middleware.WorkScheduleGuardMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'TIP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'inventory.context_processors.user_preferences',
                'inventory.context_processors.notification_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'TIP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
db_engine = os.getenv("DATABASE_ENGINE", "sqlite3").strip().lower()

ENGINE_MAP = {
    "postgresql": "django.db.backends.postgresql",
    "postgres": "django.db.backends.postgresql",
    "mysql": "django.db.backends.mysql",
    "mariadb": "django.db.backends.mysql",
    "sqlite3": "django.db.backends.sqlite3",
    "sqlite": "django.db.backends.sqlite3",
}

engine_path = ENGINE_MAP.get(db_engine, f"django.db.backends.{db_engine}")

if engine_path.endswith("sqlite3"):
    db_name = os.getenv("DATABASE_NAME")
    if db_name:
        db_name = db_name.strip()
    DATABASES = {
        "default": {
            "ENGINE": engine_path,
            "NAME": db_name or (BASE_DIR / "db.sqlite3"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": engine_path,
            "NAME": os.getenv("DATABASE_NAME", "mpt_tools").strip(),
            "USER": os.getenv("DATABASE_USERNAME", "postgres").strip(),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", "").strip(),
            "HOST": os.getenv("DATABASE_HOST", "localhost").strip(),
            "PORT": os.getenv("DATABASE_PORT", "5432").strip(),
            "CONN_MAX_AGE": int(os.getenv("DATABASE_CONN_MAX_AGE", "60").strip() or "60"),
            "OPTIONS": {
                "sslmode": os.getenv("DATABASE_SSLMODE", "prefer").strip(),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', _('Russian')),
    ('en', _('English')),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
QUALITY_REPORT_PATH = BASE_DIR / "var" / "quality-report.json"

# Redirect unauthenticated users to Django admin login.
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Gmail: задайте GMAIL_SMTP_USER и GMAIL_SMTP_APP_PASSWORD (пароль приложения Google, не обычный пароль).
# Пробелы в пароле приложения можно оставить — уберутся. Нужна 2FA в аккаунте Google.
_gmail_smtp_user = os.getenv("GMAIL_SMTP_USER", "").strip()
_gmail_smtp_app_password = (os.getenv("GMAIL_SMTP_APP_PASSWORD") or "").replace(" ", "").strip()
_use_gmail_smtp = bool(_gmail_smtp_user and _gmail_smtp_app_password)

if _use_gmail_smtp:
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_HOST_USER = _gmail_smtp_user
    EMAIL_HOST_PASSWORD = _gmail_smtp_app_password
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    _from_override = (os.getenv("DEFAULT_FROM_EMAIL") or "").strip()
    DEFAULT_FROM_EMAIL = _from_override or _gmail_smtp_user
else:
    EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost").strip()
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25").strip() or "25")
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
    EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "false").strip().lower() in {"1", "true", "yes", "on"}
    EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").strip().lower() in {"1", "true", "yes", "on"}
    DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@mpt-tools.local").strip()

# Базовый URL сайта для ссылок в письмах (уведомления о сообщениях), без завершающего слэша.
PUBLIC_SITE_URL = os.getenv("PUBLIC_SITE_URL", "").strip()

# Публичный URL Grafana для ссылки в шапке (роли «Администратор» и «Системный администратор»). Пусто — пункт скрыт.
GRAFANA_PUBLIC_URL = os.getenv("GRAFANA_PUBLIC_URL", "").strip().rstrip("/")
# Путь страницы входа Grafana для пункта меню (к базовому URL выше).
GRAFANA_MENU_PATH = os.getenv("GRAFANA_MENU_PATH", "/").strip() or "/"

# Уведомления о новых сообщениях (личных и по заявкам) на e-mail получателям.
MESSAGE_EMAIL_ENABLED = os.getenv("MESSAGE_EMAIL_ENABLED", "true").strip().lower() in {"1", "true", "yes", "on"}

ANYMAIL: dict[str, str] = {}
# При Gmail SMTP провайдеры Anymail не подключаем — одна исходящая система (см. GMAIL_SMTP_* выше).
if not _use_gmail_smtp:
    if os.getenv("ANYMAIL_BREVO_API_KEY", "").strip():
        ANYMAIL["BREVO_API_KEY"] = os.getenv("ANYMAIL_BREVO_API_KEY", "").strip()
    if os.getenv("ANYMAIL_SENDGRID_API_KEY", "").strip():
        ANYMAIL["SENDGRID_API_KEY"] = os.getenv("ANYMAIL_SENDGRID_API_KEY", "").strip()
    if os.getenv("ANYMAIL_MAILGUN_API_KEY", "").strip():
        ANYMAIL["MAILGUN_API_KEY"] = os.getenv("ANYMAIL_MAILGUN_API_KEY", "").strip()
    if os.getenv("ANYMAIL_MAILGUN_SENDER_DOMAIN", "").strip():
        ANYMAIL["MAILGUN_SENDER_DOMAIN"] = os.getenv("ANYMAIL_MAILGUN_SENDER_DOMAIN", "").strip()
    if os.getenv("ANYMAIL_POSTMARK_SERVER_TOKEN", "").strip():
        ANYMAIL["POSTMARK_SERVER_TOKEN"] = os.getenv("ANYMAIL_POSTMARK_SERVER_TOKEN", "").strip()


def _select_anymail_email_backend() -> str | None:
    """Бэкенд Anymail при заданных ANYMAIL_* ключах (или явный ANYMAIL_ESP)."""
    if not _ANYMAIL_INSTALLED or not ANYMAIL:
        return None
    priority: list[tuple[str, str]] = [
        ("ANYMAIL_BREVO_API_KEY", "anymail.backends.brevo.EmailBackend"),
        ("ANYMAIL_POSTMARK_SERVER_TOKEN", "anymail.backends.postmark.EmailBackend"),
        ("ANYMAIL_MAILGUN_API_KEY", "anymail.backends.mailgun.EmailBackend"),
        ("ANYMAIL_SENDGRID_API_KEY", "anymail.backends.sendgrid.EmailBackend"),
    ]
    esp = (os.getenv("ANYMAIL_ESP") or "").strip().lower()
    by_esp: dict[str, str] = {
        "brevo": "anymail.backends.brevo.EmailBackend",
        "sendinblue": "anymail.backends.brevo.EmailBackend",
        "postmark": "anymail.backends.postmark.EmailBackend",
        "mailgun": "anymail.backends.mailgun.EmailBackend",
        "sendgrid": "anymail.backends.sendgrid.EmailBackend",
    }
    if esp in by_esp:
        return by_esp[esp]
    for env_key, backend in priority:
        if os.getenv(env_key, "").strip():
            return backend
    return None


_email_backend_explicit = (os.getenv("EMAIL_BACKEND") or "").strip()
if _email_backend_explicit:
    EMAIL_BACKEND = _email_backend_explicit
elif _use_gmail_smtp:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
else:
    _anymail_backend = _select_anymail_email_backend()
    EMAIL_BACKEND = _anymail_backend or "django.core.mail.backends.smtp.EmailBackend"

YANDEX_MAPS_API_KEY = os.getenv("YANDEX_MAPS_API_KEY", "").strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "inventory.api.exceptions.humanized_exception_handler",
}
