# Generated by Django 5.2.11 on 2026-04-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_kind',
            field=models.CharField(choices=[('sysadmin', 'Системный администратор'), ('builder', 'Строитель')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('issued', 'Выдана'), ('closed', 'Закрыта')], default='pending', max_length=20),
        ),
    ]
