# Generated by Django 5.2.11 on 2026-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_equipmentrequest_request_kind_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrequest',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Equipment request', 'verbose_name_plural': 'Equipment requests'},
        ),
        migrations.AlterModelOptions(
            name='materialusage',
            options={'ordering': ['-used_at'], 'verbose_name': 'Material usage', 'verbose_name_plural': 'Material usage records'},
        ),
        migrations.AlterModelOptions(
            name='worktimer',
            options={'ordering': ['-started_at'], 'verbose_name': 'Work timer', 'verbose_name_plural': 'Work timers'},
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_kind',
            field=models.CharField(choices=[('sysadmin', 'Sysadmin request'), ('builder', 'Builder request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('issued', 'Issued'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
