# Generated by Django 5.2.11 on 2026-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_portal_and_i18n_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrequest',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AlterModelOptions(
            name='materialusage',
            options={'ordering': ['-used_at']},
        ),
        migrations.AlterModelOptions(
            name='worktimer',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_kind',
            field=models.CharField(choices=[('sysadmin', 'Sysadmin'), ('builder', 'Builder')], max_length=20),
        ),
    ]
