# Generated by Django 5.2.11 on 2026-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_alter_equipmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_kind',
            field=models.CharField(choices=[('sysadmin', 'Сисадмин'), ('builder', 'Стройка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('issued', 'Выдана'), ('closed', 'Закрыта')], default='pending', max_length=20),
        ),
    ]
