# Generated by Django 5.2.11 on 2026-04-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_equipmentrequestmessage_equipmentrequestphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkTimer',
        ),
    ]
