# Generated by Django 5.2.11 on 2026-04-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_delete_worktimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequestmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='operations.equipmentrequestmessage'),
        ),
    ]
