# Generated by Django 5.2.11 on 2026-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_equipmentrequest_needed_by_required'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodicmaterialusageschedule',
            options={'ordering': ['next_run_on', 'pk'], 'verbose_name': 'Периодический расход по расписанию', 'verbose_name_plural': 'Расписания периодического расхода'},
        ),
        migrations.AlterField(
            model_name='periodicmaterialusageschedule',
            name='next_run_on',
            field=models.DateField(verbose_name='Следующий запуск по расписанию'),
        ),
    ]
