# Generated by Django 5.2.11 on 2026-05-07 13:42

import operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_equipmentrequest_non_consumable_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='needed_by',
            field=models.DateField(default=operations.models.default_needed_by_date),
        ),
    ]
