# Generated by Django 5.2.11 on 2026-05-07 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_alter_periodicmaterialusageschedule_frequency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequestThreadRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_reads', to='operations.equipmentrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_request_thread_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'equipment_request'), name='ops_equipmentrequestthreadread_user_req_uniq')],
            },
        ),
    ]
